name: coffee
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  device_preview: ^1.1.0
  iconly: ^1.0.1
  sliding_up_panel: ^2.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/Rectangle 1706.png
    - assets/coffee-seed.png
    - assets/coffee-bag.png      
    - resources/mapss.png
    - resources/asf.PNG
    - resources/motorbike.png
    - resources/profile_picture.png
    - resources/Home_page.png
    - resources/Rectangle 1706.png
    - assets/Rectangle.png
    - assets/dollar.png
    - assets/discount.png
    - resources/Main_image.png
    - resources/coffee2.jpeg
    - resources/coffee3.jpeg
